#!/bin/bash
set -ex

mkdir -p vendors && cd vendors


wget -c 'https://github.com/catchorg/Catch2/archive/v2.11.1.tar.gz' -O Catch2-2.11.1.tar.gz
tar xzf Catch2-2.11.1.tar.gz
ln -sf Catch2-2.11.1 Catch2

wget -c 'https://github.com/SFML/SFML/archive/2.5.1.tar.gz' -O SFML-2.5.1.tar.gz
tar xzf SFML-2.5.1.tar.gz
ln -sf SFML-2.5.1 SFML